version: '3'

services:
  db:
    image: postgres:11.3
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    restart: always
    #Use pipenv's Python (which is Dockerfile's Python):
    command: ["/code/wait-for-postgres.sh", "pipenv", "run", "python", "/code/manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
