# Generated by Django 2.2.3 on 2019-07-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_auto_20190729_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzatype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
