# Generated by Django 2.2.3 on 2019-07-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_auto_20190729_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzatype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
